INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
Namespace(batch=64, dataset='datasets/rosbotxl_data', epochs=100, log_interval=50, lr=0.0001, noisevar=15, robustification=True)
Found data_cleaned.csv in datasets/rosbotxl_data/003
Found data_cleaned.csv in datasets/rosbotxl_data/010
Found data_cleaned.csv in datasets/rosbotxl_data/004
Found data_cleaned.csv in datasets/rosbotxl_data/000
[Errno 2] No such file or directory: 'datasets/rosbotxl_data/collection007/data_cleaned.csv' 
No data_cleaned.csv in directory datasets/rosbotxl_data/007
Found data_cleaned.csv in datasets/rosbotxl_data/008
Found data_cleaned.csv in datasets/rosbotxl_data/002
Found data_cleaned.csv in datasets/rosbotxl_data/006
Found data_cleaned.csv in datasets/rosbotxl_data/001
Finished intaking image paths!
Retrieving output distribution....
Moments of distribution: {'shape': (13576,), 'mean': 0.015624491008339942, 'median': 0.0, 'var': 0.13971973393182766, 'skew': -0.10432795641257415, 'kurtosis': 2.1464155097531936, 'max': 1.0, 'min': -1.0}
Total samples: 13576
time to load dataset: 9.77159333229065
iteration='DAVE2v3-1344x376-lr0.0001-100epoch-64batch-lossMSE-13Ksamples-INDUSTRIALandHIROCHIandUTAH-noiseflipblur'
device=device(type='cuda')
Traceback (most recent call last):
  File "training/Zach_train_DAVE2.py", line 175, in <module>
    main()
  File "training/Zach_train_DAVE2.py", line 120, in main
    outputs = model(batch_images)  # Pass the batch of images to the DNN
  File "/u/ezj2hu/ROSbot_data_collection/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/ezj2hu/ROSbot_data_collection/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/u/ezj2hu/ROSbot_data_collection/models/Zach_DAVE2pytorch.py", line 242, in forward
    x = self.conv1(x)
  File "/u/ezj2hu/ROSbot_data_collection/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/ezj2hu/ROSbot_data_collection/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/u/ezj2hu/ROSbot_data_collection/.venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/u/ezj2hu/ROSbot_data_collection/.venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.42 GiB. GPU 
